### ISSUE TITLE
Create functionality for front end to be able to update reviews

### ISSUE THREAD

**Issue by ReeceRenninger** [FullStackDevs-CodeFellows-301d97/Review-Site-FrontEnd#9]
Create a UpdateGameForm.js file on the front end to add a updateForm component, event handler, and return a form with update fields in a modal.

**Comment by s-glass** [comment]
Audrey says use userHome.js to manage the rest of the CRUD functionality for the saved games in the Users. 

Update and delete state on the home page

Set button in the modal on the userHome.js in order to do CRUD with the saved games.
